name: better_pattern_lock
description: A pattern lock for Flutter. Just like in your old Samsung device, but this one is much more customizable.
version: 1.0.1
homepage: https://github.com/scisdev/better_pattern_lock

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true